### ISSUE TITLE
Implement license validity check

### ISSUE THREAD

**Issue by niksauer** [niksauer/serverless-software-license#3]
- [x] Implement the `LicenseManager`'s `checkValidity` method by:

1. checking if the license retrieved from storage passes the address ownership challenge (see `verifyOwnership` in `src/lib/util.ts`)
2. checking if the address referenced in the license has a license according to the registry associated with the manager (see `hasLicense` in `src/lib/LicenseRegistry.ts`) 
3. setting the private `_isValid` property according to the conditions met
4. emitting a `LicenseManagerEvent.LicenseValidityChanged` event if the `_isValid` property changed compared to before calling this method

- [x] Create a test case verifying that the `isValid` property returns a boolean in any case
- [x] Create a test case verifying that the `isValid` property returns true if the conditions above are met
- [x] Create a test case verifying that the `isValid` property returns false if any of the conditions above aren't met

**Comment by ahmadbassir** [comment]
```
async checkValidity(): Promise<void> {
    const license = await this.storage.getLicense();

    const ownsAddress = verifyOwnership(
      license.challenge,
      license.challenge.response
    );

    if (!ownsAddress) {
      this.setIsValid(false);
      return;
    }

    const ownsLicense = await this.registry.hasLicense(
      license.challenge.address
    );

    if (!ownsLicense) {
      this.setIsValid(false);
      return;
    }

    this.setIsValid(true);
  }

  // MARK: - Private Methods
  private setIsValid(value: boolean) {
    this._isValid = value;
    this.emitter.emit(LicenseManagerEvent.LicenseValidityChanged, value);
  }
```

**Comment by niksauer** [comment]
Please set:


```
const challenge = license.challenge
const address = challenge.address
```

before evaluating conditions.

**Comment by niksauer** [comment]
Commited to https://github.com/niksauer/serverless-software-license/tree/feature/license-validity-check.
